
---
test:
  name: dsfasfasdfsdfa
  description: This is a helloworld benchmark of FISCO BCOS for caliper
  clients:
    type: local
    number: 1
  rounds:
  - label: set
    description: Test performance of setting name
    txNumber:
    - 1000
    rateControl:
    - type: fixed-rate
      opts:
        tps: 1300
    callback: set.js
monitor:
  type:
  - docker
  docker:
    name:
      - node0
      - node1
      - node2

  process:
    - command: node
      multiOutput: avg
  interval: 0.5
